### ISSUE TITLE
[고민]: category 추가 방식

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-backend#128]
## 고민 사항 

이전에 저희가 카테고리를 만들 때 

1. 카테고리 목록을 생성하고
2. 카테고리 추가

의 방식으로 사용하였는데 현재 바뀐 화면 기준으로는 카테고리 목록을 생성하는 플로우가 불필요 합니다.

<img width="1448" alt="image" src="https://github.com/pickly-team/pickly-backend/assets/54137044/695979dd-a078-4839-8201-64912550fb51">

현재 프론트 화면을 본다면 categoryId를 필요로 하지 않아서
해결 방법으로 생각나는건 

1. 카테고리 ID에 대한 삭제 -> 하나의 리스트만 가지고 처리 하도록
2. 추후의 확장성을 고려하여 지금과 같이 사용하고 `caegoryId 1` 기반으로 프론트에서 모든 카테고리 처리
- 현재 이 방식도 리스트에 카테고리 이모지가 날라오지 않아 수정이 필요합니다 🫠

### 여러분의 생각은 어떤가요?

<img width="300" alt="image" src="https://github.com/pickly-team/pickly-backend/assets/54137044/2882c27c-e3af-42b7-8a18-71e5e33c1bf2">

**Comment by JoeCP17** [comment]
1. 불필요한 Response 제거를 한다. ( category Id, member Id ) 

Member Id의 경우 기존 파라미터 값으로 이미 받고있기에, Response 내의 Id값은 불필요하다. 

2. 현재 서비스 상에서는 순서 조정 이벤트가 발생하는데 순서 조정후 저장할 수 있는 요소가 필요할 것 같다. 

이정도인것 같습니당

**Comment by EunjiShin** [comment]
> 1. 카테고리 ID에 대한 삭제 -> 하나의 리스트만 가지고 처리 하도록

/api/categories/{categoryId} API를 삭제하고, /api/categories 하나만 사용한다는 말씀이시죠?
저는 좋은 방법이라고 생각합니다. 요소가 1인 카테고리 리스트를 등록하는 개념이니 해당 API의 본래 목적과 크게 차이가 없다고 봐요!

> 2. 추후의 확장성을 고려하여 지금과 같이 사용하고 caegoryId 1 기반으로 프론트에서 모든 카테고리 처리

이것은.. 제가 이해하지 못했습니다
API endpoint의 categoryId는 REST 원칙을 따른 것 뿐이지 실제 백엔드 로직에선 사용되지 않으니, 프론트에서 endpoint 양식을 맞추기 위해 1이라는 더미값을 보낸다는 뜻일까요? 만약 그렇다면 오히려 기능을 이해하기 어려워질 것 같고, 큰 메리트가 없는 것 같아 반대합니다..!


그런데 제가 알기로 `/api/categories/{categoryId} ` 는 카테고리 단일 추가 API가 아니라, **특정 카테고리 수정 API**인 것으로 알고 있어요. 해당 API는 처음부터 카테고리 추가 목적으로 만들어진 것이 아니라서, 루벤이 의견주신 1번 방식으로 가도 되지 않을까 싶어요?

POST method라 혼란의 여지가 있는 것 같은데,[ 코드리뷰 기록](https://github.com/pickly-team/pickly-backend/pull/23#discussion_r1118360274)을 보니 다음 PR에서 메소드 변경해도 될 것 같네요!

**Comment by ww8007** [comment]
@EunjiShin 
네 맞아요 api를 일단 하나만 사용해도 괜찮을 것 같아요
말씀해주신 것 처럼 2번은 별로인거 같아서 api를 변경하는 방향이 맞는거 같네요

다만 현재 swagger를 보시면
`[POST] /api/categories`
```json
{
  "memberId": 0,
  "name": "string"
}
```
`[POST] /api/categories/{cateogyId}`
```json
{
  "isAutoDeleteMode": true,
  "name": "string",
  "emoji": "string"
}
```
이렇게 되어 있어서 수정이 아니라 post가 맞는거 같긴 한데 
저는 `[POST] /api/categories` 쪽에 emoiji가 추가되어야 할 것 같네요.
(현재 이모지를 추가할 수 없음)

그리고 `[GET] /api/categoires` 에도 다음과 같아서 수정이 필요해 보여요.
1. emoji가 없음
2. 개인이 요청하는 것 이기 때문에 memberId가 필요없음
3. categroyId 필요없음
```json
{
  "hasNext": false,
  "contents": [
    {
      "categoryId": 5,
      "memberId": 1,
      "name": "리액트 카테고리"
    },
    {
      "categoryId": 4,
      "memberId": 1,
      "name": "안녕하세요"
    },
    {
      "categoryId": 3,
      "memberId": 1,
      "name": "이것은 카테고리"
    },
    {
      "categoryId": 2,
      "memberId": 1,
      "name": "프론트엔드"
    },
    {
      "categoryId": 1,
      "memberId": 1,
      "name": "백엔드"
    }
  ]
}
```

**Comment by ww8007** [comment]
추가적으로 순서 편집의 기능도 필요해서 
담당자 께서는 확인해주시고 추가해주시면 감사하겠습니다!

<img width="300" src="https://github.com/pickly-team/pickly-backend/assets/54137044/0bbcac38-dcb4-4c41-a6d7-bc0691f62be0"/>

**Comment by EunjiShin** [comment]
@ww8007 

해당 API에서 사용되는 메서드명이 update고, PR 코멘트에도 PUT이나 PATCH가 언급되어서 update API라고 생각했어요!
만약 해당 API를 수정 기능 용도로 쓰지 않고 있다면, 아예 기존 API에서 customerId를 제외하고 단일 카테고리 생성 API로 재활용해도 문제 없을 것 같습니다.

카테고리 순서 편집 API의 경우, 지난 정기 미팅에서 @SoobinJung1013 이 마무리 작업 해준다고 했던 것 같은데 확실하지 않네요.
만약 담당자 없는 상황이라면 적당히 백엔드에서 분배해서 작업 시작하겠습니다~

그럼 백엔드에서 처리해야 할 태스크 확인 부탁드립니다.

1. `[POST] /api/categories/{cateogyId}` 의 **단일 카테고리 추가 API로 재활용 여부** 결정 ( => 프론트엔드 응답 받은 후 결정)
2. ` [GET] /api/categoires` 의 response 필드 수정 ( => emoji 추가, categoryId & memberId 삭제)
3. 카테고리 순서 편집 API

**Comment by ww8007** [comment]
@EunjiShin 
네 말씀해주신 3개 맞는거 같아요!
추가적으로 카테고리를 여러개 생성할 수 있는 api도 필요할 것 같아요.
맨 위에 스크린샷 처럼 저희가 단일 카테고리만 생성하는 것이 아닌 여러개의 카테고리도 생성이 가능하니
이것도 한 번 확인해주시면 감사하겠습니다 😃

**Comment by EunjiShin** [comment]
@ww8007 

넵 그래서 `[POST] /api/categories/{cateogyId}`를 사용하지 않는다고 결정되면, `[POST] /api/categories` 를 수정할 생각입니다.
RequestBody에서 새로 등록할 카테고리 정보를 Array 형태로 받도록 수정하면 될 것 같아요~

해당 API 언제까지 수정 반영되어야 할까요?

**Comment by EunjiShin** [comment]
@ww8007 요거 해결되었다면 close 부탁드립니다!
