### ISSUE TITLE
[Bug]: Swagger의 기본 요청이 http 입니다

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-backend#153]
## 문제 상황

현재 https가 적용된 swagger 문서에서 api 요청을 하면 http로 요청이 가서 오류가 나네요 🫠

![image](https://github.com/pickly-team/pickly-backend/assets/54137044/090b2349-c276-4b86-924f-7e1a84c307c1)

![image](https://github.com/pickly-team/pickly-backend/assets/54137044/69a57d4e-31a9-4e15-b3b6-0c9eba0a51ef)

## 관련 문서 (제공)@litsynp 
https://stackoverflow.com/questions/70843940/springdoc-openapi-ui-how-do-i-set-the-request-to-https

**Comment by EunjiShin** [comment]
확실하진 않은데, SwaggerConfig 설정을 해줄 때 서버 url을 자동으로 따라가게 하는 설정을 추가해주면 될 것 같아요.
이전 프로젝트에선 항상 그 설정을 넣어줬는데 이번엔 나중에 인증 관련 요소 처리할 때 하려고 설정파일 내부를 다 비워놨거든요..!
한번 PR 남겨보고, 해결 되는지 체크해볼게요!
