### ISSUE TITLE
[BUG]: 차단 유저 목록 조회 API가 동작하지 않습니다.

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-backend#189]
## API

```md
/member/blocks/{blockerId}
```

## 요청 사항

- api가 올바르게 동작하지 않는 것 같습니다.
- 현재 swagger, postman 기준으로 요청을 보내도 400만 떨어지네요 😂

- 만약 수정하게 된다면 `blockerId`가 아닌 `memberId`를 query parameter로 사용해도 괜찮을까요?
- 그리고 추가적으로 `cursorId`, `pageSize`로 네이밍을 통일해도 좋을 것 같아요!

### 요청
```md
http://localhost:8080/api/member/blocks/1?cursor=0&size=10
```
### 응답
```json
{
    "timestamp": "2023-07-17T04:53:38.808+00:00",
    "status": 400,
    "error": "Bad Request",
    "path": "/api/member/blocks/1"
}
```

**Comment by JoeCP17** [comment]
접수 완료. 작업을 진행합니다.
