### ISSUE TITLE
[BUG]: 팔로워, 팔로잉 리스트 조회 API에서 닉네임이 이상한 형태로 내려 옵니다.

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-backend#195]
## 오류 사항

```json
{
    "hasNext": false,
    "contents": [
        {
            "memberId": 2,
            "loginId": "test2",
            "emoji": "😳"
        },
        {
            "memberId": 5,
            "loginId": "tkqiWPRMdjd4ItocK8V5FtZkLKt2", // 까루11로 설정된 닉네임
            "emoji": "🐶"
        }
    ]
}
```

**Comment by EunjiShin** [comment]
이슈 남길때 어떤 request로 보냈는지도 함께 남겨주세요~

**Comment by EunjiShin** [comment]
loginId는 username입니다. 현재 해당 API는 member Id (PK), member username, member emoji 이렇게 세 필드를 보내고 있어요.
까루11로 나오길 원하신다면 nickname을 리턴하도록 수정해야합니다. 
의도하신 바가 맞는지 확인 부탁드립니다!

<img width="1442" alt="스크린샷 2023-07-20 오후 1 48 33" src="https://github.com/pickly-team/pickly-backend/assets/38103085/37886bc4-639b-46c4-9057-ff18f2ea7677">

**Comment by ww8007** [comment]
네 말씀 하신대로 nickname을 return 하고 싶습니다.
유저가 친구를 찾으려고 할 경우 nickname 정보로 유저를 검색하는게 맞는거 같아서
이렇게 수정 부탁 드려도 될까요?

**Comment by EunjiShin** [comment]
넵! 그럼 loginId를 제외하고 nickname을 보내도록 수정하겠습니다
