### ISSUE TITLE
[BUG] Timezone 관련 이슈

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#206]
### 이슈
- prepersist, preupdate를 사용해서 kst를 지정해줬는데도 배포 이후 확인했을 때 utc로 저장됨

### 원인
- Prepersist, preupdate는 jpa 한정으로 동작
- 따라서 jdbc bulk insert하는 코드에는 동작하지 않음 -> DB 자체 current_timestamp 설정이 동작 -> utc
- 실제로 bulk insert가 아니라 단순 jpa save를 사용하는 코드는 정상적으로 KST가 들어옴
- data.sql로 들어가는 더미데이터도 DB 자체 current_timestamp를 이용하기에 DB 타임존을 따르게 된다.

### 해결
- Postgresql timezone을 Asia/Seoul로 변경
- ddl이긴 하지만, 운영 중인 DB에 timezone 변경 명령을 올려도 기존 데이터는 영향받지 않아 걱정했던 부하는 없을 것으로 예상

### 고려할 점
- 만약 KST -> UTC로 시간대를 바꿔야 할 경우
  - 기존에 저장된 시계열 데이터를 전부 수동 업데이트 해주어야 함
  - DB의 restart 필요

### 또 다른 해결 방법
- jdbc 사용 코드, data.sql에만 직접 created_at, updated_at, deleted_at 을 지정해주는 방법
  - data.sql에서 번거로워짐
  - jdbc 특성상, timezone 정책이 달라지면 직접 문자열 코드를 하나하나 수정해줘야 함

### 최종
- UTC를 디폴트로 사용
- member 정보에 timezone을 함께 저장
- 화면단에 시간 정보 보내줄 땐 member.timezone을 이용해 변환

**Comment by ww8007** [comment]
흠 이런 이슈가 있었군요...
만약 차후를 고려 한다면 UTC로 가져가는게 훨씬 좋아보이긴 하네요
일단 프론트에서의 테스크들은 이전보다 조금 여유가 있을 것 같아서
이 부분은 @EunjiShin 님이 판단하시고 KST와 UTC 중 선택해 주셔도 될 것 같아요!

**Comment by EunjiShin** [comment]
@ww8007 그럼 초기 정책을 따라 UTC로 수정하겠습니다! 확인 감사합니다 🙌
