### ISSUE TITLE
[고민] Postgres @Lob (text type) 이슈

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#30]
## 발생 이슈
`org.postgresql.util.PSQLException: Bad value for type long: x`

## 위치
- Bookmark Entity의 url, preview image 필드를 text 타입 (JPA에선 @Lob)로 지정함
- 쿼리 조회시, 데이터 결과물과 Entity 매칭에 실패

## 원인
- @Lob의 경우, Hibernate는 CLOB로, postgresql jdbc driver는 Large Ojbect 생성 후 oid (long)을 사용
- java에서 String으로 문자열을 사용하는 것과 Hibernate가 long 타입으로 변환하는 것이 충돌하게 됨

## 고민
1. 일차원적인 해결 방법은 text 컬럼을 oid 필드로 마이그레이션하는 방법
2. 하지만 좀 더 본질적으로, 북마크 url과 북마크 프리뷰 url에 @Lob가 필요한지를 논의해야 함
  - url에 최대 4GB의 용량을 할당할 필요가 있는가? 
  - 만약 그렇다 해도, 그렇게 긴 url을 화면 UI에 뿌리는 것이 옳은가?
  (...으로 축약하더라도, 하이퍼링크 이동을 위해 클라이언트단에서 원본 url을 가지고 있긴 해야함)
  - url 축약이 필요하다면, 어떻게, 그리고 어디서 수행할 것인가? url 단축키를 구현할 것인가?

**Comment by ww8007** [comment]
단축 url에 대해서는 네이버에서 일 25,000건에 대해서 제공을 하긴 하네요
저도 굳이 full url 주소를 매번 저장을 하는 방식은 비효율 적일 것 같네요 🧐
1. 이런 서비스를 여러개 찾아서 등록하는 것과 
2. 직접 구현...?

일단 관련 링크 첨부하도록 하겠습니다.
[네이버 URL API](https://developers.naver.com/docs/utils/shortenurl/)
[JS URL 줄이기](https://coder38611.tistory.com/67)

**Comment by litsynp** [comment]
일단 직접 구현하는건 최대한 줄여보는 걸로 하고, URL 길이 제한을 서버/클라 둘 다에 두는 건 어떨까요? 2000자 정도가 사실상 맥스(de facto)라고 하긴 하는데...([링크](https://stackoverflow.com/questions/417142/what-is-the-maximum-length-of-a-url-in-different-browsers))

**Comment by EunjiShin** [comment]
**온라인 미팅 협의 결과**

1. MVP 개발 단계에선 2000자 제한을 둔다
2. 추후 고도화할 때 2000자 이상이면 URL 단축 기능을 사용하도록 수정한다
