### ISSUE TITLE
[고민] 페이징 구현에 필요한 Request, Response 관련

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#31]
## 발생 이슈
`org.springframework.data.domain`의 `Pageable`, `Page`, `Slice` 의 효율성

## 위치
bookmark 전체 조회, 좋아요한 bookmark 전체 조회 등 `많은 데이터를 화면에 뿌려야 하는 모든 API`

## 원인
- JPA에서 쉽고 간단하게 페이징 구현을 위해 보통 `org.springframework.data.domain.Pageable`을 사용함
- 근데 이 친구들은 포맷이 정해져있음. 내게 필요하지 않더라도!

ex. request로 Pageable 객체를 받고, response로 Slice를 돌려줄 때 아래와 같이 요구 포맷이 정해짐.

**[ request ]**
```
{
  "page": 0,
  "size": 1,
  "sort": [
    "string"
  ]
}
```

**[ response ]**
```
{
  "size": 0,
  "content": [
     // 조회 데이터 포맷
  ],
  "number": 0,
  "sort": {
    "empty": true,
    "sorted": true,
    "unsorted": true
  },
  "pageable": {
    "offset": 0,
    "sort": {
      "empty": true,
      "sorted": true,
      "unsorted": true
    },
    "pageNumber": 0,
    "pageSize": 0,
    "paged": true,
    "unpaged": true
  },
  "first": true,
  "last": true,
  "numberOfElements": 0,
  "empty": true
}
```

request는 뭐 그렇다쳐도, response에는 불필요한 데이터가 너무 많음...! 

## 고민
- 위 같은 상황에서, 개발 편의를 위해 여전히 Pageable, Slice...등을 사용하는 것이 옳은 일인지?
- 조금 번거롭더라도, 내게 필요한 필드만 남겨둔 커스텀 페이징 객체를 쓰는게 좋지 않을까?
- 프론트엔드에서 페이징을 처리하기 쉽도록, 전체 페이징 API들은 공통 포맷을 가져야 한다. 
=> 따라서 위 사항을 결정한 후, 필요에 따라 기구현된 API의 수정을 진행해야 한다.

**Comment by ww8007** [comment]
![image](https://user-images.githubusercontent.com/54137044/221428513-e4d3731f-9a22-42b1-a7be-0d9db40ec7b1.png)
요게 포켓몬 도감 리스트?에 사용되는 페이지네이션 된 api 인데 response를 비교해보면 너무 크긴 하네요
이 부분은 개발을 해보시고 싶으신 분이 디자인 패턴을 이용해서 구현을 해보시는 것도 좋을 듯 하네요 😃

[포켓몬 도감 api](https://pokeapi.co/docs/v2)

**Comment by litsynp** [comment]
개발 편의상엔 좋은데 기본 Pageable 객체에서 안쓰는 게 너무 많아서... 새로 만드는 것도 좋지 않을까 싶네요.

**Comment by EunjiShin** [comment]
**온라인 협의**

1. 커스텀 페이징 객체 사용 (페이징 request, 페이징 response)
2. 데이터 들어가는건 제네릭으로 처리
