### ISSUE TITLE
[discussion] 북마크 타이틀 크롤링 로직 관련

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#319]
### 주제

Fly.io 이관 이후 전반적인 서버 레이턴시 증가함에 따라 메인 기능인 북마크 추가 기능의 성능 개선을 위해, 크롤링 로직을 프론트로 이관하는 방법 논의해보기

### 추가 고려할 점

- 만약 이관하지 않을 경우, 어떻게 성능을 개선할 것인가?
- 비공개 url을 추가하는 방법은?

**Comment by ww8007** [comment]
## 의견

### 북마크 제목을 받아오는 API는 프론트에서 처리를 하여도 괜찮을 것 같다.

> 이유 

제목을 받아오는 api를 굳이 서버로 요청을 보내서 받아올 필요가 없음
익스텐션에서는 프론트 자체에서 og 태그와 타이틀을 넘겨받는 식으로 처리가 가능하고(앱에서는 어려울 것 같음)
url이 변경될 때 마다 api 요청을 보낼 필요성 자체가 없어짐

물론 프론트에서 url을 입력 받을 시 올바른 주소인지, https 형식인지와 같은 기본적인 처리는 진행할 예정

속도 측면에서 `fly.io`로 이관함에 따라 나온 문제이긴 하지만 프론트로 이관하게 된다면 `장점`은 아래와 같음

1. 굳이 `서버 api call`을 늘리지 않아도 된다는 점
2. `fly.io`를 이용 하더라도 타이틀 자체만큼은 속도에 영향을 받지 않음
3. 제목을 받아오는 것에 대해 `자율성`을 가질 수 있다는 점
- 익스텐션 같은 경우에 현재 방문한 페이지의 title을 받아올 수 있음
- 아마 핸드폰 공유하기 기능도 가능할 것이라 예상

---

### 비공개 url을 추가하는 방법은?

저장하는 북마크에 대해서 검증을 진행해야 할 필요성이 그렇게 크지 않다고 생각함
일단 크롬 북마크를 예시로 들자면 사용자가 방문한 사이트에 대해서 어떠한 북마크인 경우에도 저장이 가능하게 되어있음
하지만 현재 서비스의 경우 현재 서버에서 url을 검증하게 될 때 비공개 북마크 자체를 valid하지 않은 url이라고 판단하여 저장을 할 수 없는 상황임
우리의 서비스 성격상 기존에 우리가 사용하던 크롬과 같이 `북마크를 편리하게 관리할 수 있다는 것이 장점`인데 
어느정도 제약이 생긴 상황

1. fly.io를 이용하며 얻는 비용적인 장점과 
2. 사용자에게 북마크 추가에 대한 자율성을 부여하는 것
이 주된 목적이라고 생각함

> 비공개 북마크일 경우 기본적으로 
1. 지금과 같은 형태로 시간을 기본값으로 지정함
2. 사용자가 강제로 입력을 하도록 하게 함(안내 문구를 같이 toast로 띄워줌 - 제목을 받아올 수 없는 url)
같이 처리하게 된다면 괜찮을 것 이라고 판단함.

> 안전성에 대한 문제는 
1. 우리가 서버에서 url 정보에 대해서 영향을 받는 점이 없음
- 서버에서 악의적인 url 주소가 입력된다 할지라도 영향 받는 요소 자체는 없음
2. 북마크 신고 기능
- 북마크가 문제가 있을 경우 영향을 받는 부분은 사용자임
- 해킹을 당하여 내 북마크나 친구의 북마크 주소가 변경되거나 추가되지 않을 경우 이상한 북마크에 접근할 위험성 자체가 많이 없음
(기본적으로 내 북마크와 친구 관계의 북마크만 지금 볼 수 있기 때문에)
- 북마크를 신고하여 그 북마크 url의 경우 따로 저장을 하고 그러한 북마크들만 저장될 때 필터링을 거치게 한다면 이것도 어느정도 해결 할 수 있다고 판단함

**Comment by EunjiShin** [comment]
### 의견
- 크롤링 로직은 서버 책임으로 유지해야 한다.

---
### 이유1
- **현재 문제의 배경은 fly.io 이관으로 인해 전반적인 서버 지연이 발생한 것이지, 크롤링 api 하나의 문제는 아니다.**
  - 따라서, 지금 크롤링 로직을 프론트로 이관하더라도, 북마크 추가 등 다른 api는 그대로 지연이 발생할 것이며, 이는 결국 근본적인 해결 방법이 아니다.
  - 실제로, 들어온 qa는 타이틀 크롤링이 아닌 **북마크 추가에서 응답이 느리다** < 는 문의였다.

### 이유2
 - **서버측  api의 성능 개선 여지가 있다.**
   - QA에 따르면, 지금 문제가 되는 건 북마크 생성 api다. 현재 북마크 생성 유저 플로우는 아래와 같다.
     - 프론트에서 입력 url로 북마크 타이틀 받아오는 api 호출
     - 서버는 입력 url을 크롤링한 후, 받아온 타이틀을 반환
     - 프론트에서 받은 타이틀을 이용, 북마크 생성 api 호출
     - 서버는 입력 url을 크롤링하여 타이틀, 썸네일 정보를 받아오고, 이 정보를 이용해 북마크를 생성한다.
- 이는 북마크 생성 api가 만들어진 후, 이후 ui 변경에 따라 (유저가 타이틀을 변경할 수 있게 해달라는 QA 반영) url로 타이틀 조회 api를 추가 개발하는 과정에서 변경된 로직이다.
     - 1차 release가 완료된 지금, 북마크 타이틀 조회 api 없이 북마크 생성 api가 단일 호출되는 플로우는 없다. 따라서, 타이틀 조회가 항상 북마크 생성 api 호출보다 선행된다고 가정할 수 있다.
- 이런 배경 아래서, 전체 플로우를 아래와 같이 변경하여 북마크 생성 과정에서의 불필요한 크롤링 과정을 줄일 수 있다.
     - 프론트에서 북마크 정보를 받아오는 api 호출
     - 서버는 입력 url을 크롤링하여, 타이틀과 썸네일을 반환한다.
     - 프론트는 타이틀과 썸네일 정보를 이용, 북마크 생성 api를 호출
     - 서버는 request 값을 이용해 바로 북마크를 생성한다.
       - 이때 서버는 request url에 대해 http connect가 아닌, 정규식을 이용한 검증을 수행한다.
       - 검증을 수행하는 이유 : 악의적인 접근 또는 테스트를 위해 클라를 거치지 않고 서버로 바로 api를 call하는 상황을 배제할 수 없다. jpa를 사용하며 sql injection 피해 가능성은 줄었으나, 멀쩡히 저장된 북마크가 앱 내에서 불러와지지 않는다면 사용자가 의아할 수 있을 것 같다. 타이틀 크롤링에 실패할 경우 디폴트 타이틀을 직접 만들어 사용하므로, 타이틀의 유무로는 정상적인 페이지인지를 판단할 수 없으니 추가 검증이 필요하다고 생각했다.

### 이유3
- **비즈니스 로직의 분산은 유지보수 및 기능 확장을 어렵게 만든다.**
  - 이유 2에서 언급한 로직에 따르면, 프론트에서 북마크 정보를 받아오는 api 호출 < 이 과정을 프론트에서 직접 크롤링 하는 방식으로 사용하면 전체 북마크 생성 flow의 레이턴시를 더욱 줄일 수 있지 않을까 생각했다.
  - 하지만 북마크 크롤링 (타이틀, 썸네일) 영역은 북마크 생성 로직과 밀접하게 관계되어 있다.
    - 크롤링에 실패한 경우, 유저의 시간대 + 현재 시간을 이용해 서버에서 디폴트 타이틀을 생성해야 하는 방식
  - 위와 같은 로직을 일부 프론트로 이관할 경우, 북마크 생성과 관련하여 오류가 발생한다면 프론트와 서버 둘 다를 수정 또는 디버깅해야 한다. 
  - 만약 북마크 생성과 관련된 정책이 변경된 경우도 마찬가지다. 
 - 이와 같은 상황에서, 서버 api에 개선 여지가 있다면 서버 최적화가 우선되어야 할 것 같다.
  - 서버 최적화 이후에도 성능 이슈가 발생한다면 그때 프론트 일임 여부를 논의하면 어떨까?

---
### 고려 사항에 대한 대응
- 이유 2에서 언급한 로직으로 대체한다면 비공개 url도 추가할 수 있다.
- 이유 2에서 언급한 로직으로 대체한다면 api 자체 성능 개선이 가능하다.

**Comment by EunjiShin** [comment]
## 결론 (2023.10.26)

### 수정된 북마크 추가 flow

1. 프론트엔드에서 입력 url을 크롤링하여 title, thumbnail을 받아온다.
2. 받아온 정보를 이용해 북마크 생성 API를 호출한다.
2-1. 만약 title을 크롤링하는데 실패한 경우, title 필드에 null을 담아 보낸다. 
3. 서버는 request를 이용해 북마크를 저장한다.
3-1. request의 url을 정규식을 이용해 올바른 url인지 검증한다.
3-2. request의 title이 null일 경우, 로그인 유저의 timezone 정보를 이용해 디폴트 title를 생성한다.

### 이렇게 결정한 이유
1. 북마크 생성 API 뿐만 아니라, 북마크 정보 조회 API의 성능 개선도 필요하다.
2. url을 이용한 공격은 아래 이유로 발생할 가능성이 낮기에 서버 역할을 줄여도 된다.
2-1. JPA를 사용하기에 SQL injection 방어 가능
2-2. 보통 악의적인 공격은 url endpoint가 아니라, url로 불러온 페이지 내에 스크립트를 심는 방법으로 구현된다. 따라서 url 자체의 health check로는 어차피 공격을 감지할 수 없다.
3. 데이터 fetch 이외의 비즈니스 로직은 서버에서 가져가는 것이 맞기에, 디폴트 타이틀을 만드는 로직은 서버에 유지한다.
4. 클라이언트에서 직접 북마크를 크롤링할 경우, 크롬 프로세스에 저장된 사용자 정보를 이용해 비공개 페이지에도 접근할 수 있다.
4-1. 예를 들어, github privatae repo에 접근할 경우, 내가 크롬에 로그인 되어 있다면 바로 접속이 된다. 하지만 서버는 깃허브 자체의 로그인 정보가 없으므로, 200 Ok가 아니라 404 not found가 떠서 url health check에 실패할 것이다.
