### ISSUE TITLE
[feat] 북마크 자동 삭제 기능

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#42]
## 기능 설명
아래 해당되는 경우, 유저가 특정 북마크를 읽으면 해당 북마크를 삭제한다.

1. 유저의 읽은 북마크 자동 삭제 설정이 on인 경우
2. 특정 카테고리에 북마크 자동 삭제 설정이 on인 경우

## To do
~~북마크 상세조회 메서드에 북마크 삭제 코드 추가~~
=> 코멘트 참고 : 개발 취소

**Comment by EunjiShin** [comment]
((( 논의 필요 ))) @pickly-team/backend-team 

1. 북마크 상세 조회 메서드 내부에 해당 북마크 삭제 로직을 추가할건지?
2. 프론트엔드에서 북마크 상세 조회 API를 호출한 이후에, 북마크 자동 삭제 API를 호출하게 할건지? (자동삭제 API에서 삭제 조건 체크)
3. 이외에 다른 방법이 있는지?

**Comment by JerryK026** [comment]
개인적인 생각으로는 처음에는 객체들 간의 유기적인 관계로 봤을 때는 이것도 도메인 로직이기 때문에 백엔드에서 담당하는 것이 좋다고 생각했으나, 어차피 이것도 FE에서 관리한다면 로직을 수행한다는 것은 똑같기 때문에 큰 상관 없을 것 같고, FE 단으로 분리해서 처리하면 로직 자체가 간단해지기 때문에 그것도 나름대로 좋은 것 같습니다.
개인적으로는 백엔드에서 처리하는 게 조금 더 좋지 않나 하는 생각이지만요 ㅎ

**Comment by EunjiShin** [comment]
@JerryK026 
아 저도 백엔드에서 처리하는게 좋다고 생각해요! 근데 이슈를 남긴 이유는 **유저 플로우가 꼬인다고 생각**해서요! 🤔

예를들어, 유저가 북마크 상세 조회를 하고, 거기서 북마크 내용을 수정하려고 하는 경우가 있습니다. 이때 북마크 상세 조회를 했기 때문에 백엔드단에서 해당 북마크를 바로 삭제하면, `유저는 화면에서 해당 북마크를 보고 있는데도 수정을 할 수 없게 됩니다`. 
삭제된 북마크라고 에러가 뜰거에요. 당장 화면에 데이터가 있는데도, 없는 북마크라서 수정이 안된다고 하면 그건 확실히 시스템 오류니까요 😇

해서 이런 상황을 감안하더라도 `백엔드가 삭제하는게 좋은지`, 아니면 `위 상황을 방지하기 위해 API를 나누는게 좋을지` 고민되어서 이슈로 남겼어요~

만약 API를 나눠서 FE가 관리하게 한다면 로직이 이렇게 될 것 같아요👀
1. 북마크 상세 조회
2. 수정, 삭제 등 요청 수행
3. 상세 조회 페이지를 벗어날 때 (= 해당 북마크에 더 이상 볼 일이 없을 때) 북마크 삭제 API 호출

**Comment by EunjiShin** [comment]
[ 온라인 정기 미팅 협의 ]

- 2안 채택 (상세페이지 벗어날 때 삭제 API 호출)
