### ISSUE TITLE
[고민] 노말 / 하드모드 on & off 구현중 유저의 status 상태에 대한 고민입니다. 

### ISSUE THREAD

**Issue by JoeCP17** [pickly-team/pickly-backend#47]
# 서론 
- 노말 / 하드 모드 구현 도중 해당 유저가 현재 어떤 상태의 읽기를 진행중에 있는지 상태값을 어떻게 관리해야할지 고민이 생겼습니다. 
- 고민한 발생한 부분은 아래 현재 저희가 구상했던 ERD에서 발생했습니다. 

![Untitled](https://user-images.githubusercontent.com/76832303/222767981-4bc43da9-18f7-4890-884a-58bdc7a1d8d7.png)

# 본론 

## 1번 
- 생각한 방법중 하나는 다음과 같습니다. 
- mode_status ( 가제 ) 테이블을 추가합니다. 
- 해당 테이블의 주요 칼럼은 member_id, mode_status (Boolean ) 으로 구분지어 status값을 관리합니다. 

## 2번 
- on / off 관련된 세팅 status를 하나의 테이블에 0, 1 로 관리합니다. 
- 현재 on / off 정책이 4개 ( 친구 알림, 모드관리, 읽은 즐겨찾기 자동 삭제설정, 카테고리 전체에 즐겨찾기 자동 삭제 모드 설정 )으로 알고있어서 그렇게 칼럼이 많지는 않을것 같단 생각이 들었습니다. 
- 다만, 친구 알림같이 Push 발송시 TOPIC 발송으로 처리하는 항목인 경우는 이 부분을 위해 ENUM값으로 관리하는것이 발송시 어플리케이션 내 레이턴시를 줄일수 있는 요소가 될 수도 있을것같단 생각을 했어요! 

혹시 제가 놓치고있었던 부분이나 결론이 났었던 사항들이 있다면 알려주시면 감사합니다. ( _ _ ) 
다른분들은 어떻게 생각하시는지 의견 남겨주세용!

**Comment by JoeCP17** [comment]
++ Slack , Discord , Notion해서 한번 슥 훑어봤었는데 따로 나와있는게 없었던 것 같아서... 혹시나 제가 못찾는거일수도 있을것같아 만약 관련 내용이나 참고할만한 내용이 있다면 댓글로 남겨주셔도 너무나 좋습니다 !

**Comment by SoobinJung1013** [comment]
현재 DB schema가 업데이트가 안되어있는 상태입니다. 
코드상에서 확인해보실 경우 Member 테이블에 하드모드/노말모드 관련 컬럼이 있긴합니다 !
```
@Column(name = "is_hard_mode", nullable = false)
private Boolean isHardMode;
```

**Comment by JoeCP17** [comment]
@EunjiShin @litsynp @SoobinJung1013 

확인 현재 완료했습니다!! ( _ _ ) 현재 코드 파악해보면서 진행중인데 아까 말씀드리려고했는데 제가 경황이 없어 이쪽에 태그걸고 의견 남겨봅니당 

현재 on / off 정책은 다음과 같습니다! 
- 친구 알림 , 모드관리, 읽은 즐겨찾기 자동삭제 설정 , 카테고리 전체에 즐겨찾기 자동 삭제 모드 

현재 Member 부분에는 hard 모드 외 , 따로 on / off 에 대한 stauts 관리가 존재하지 않아서 만약 해당 컬럼을 Member 에 다 추가한다면 많이 뚱뚱해질 것 같단 생각을 했어요! 

그래서 MemberStatus로 분리하여 위 4개의 status를 한번에 관리할 수 있도록 분리하여 작업을 진행해보려고해요!! 

책임감있게 진행하는게 목표이긴하나, 이렇게되면 Member 테이블도 침범하는 요소가되어서 의견남기고자 태그를 걸게되었습니다! 

혹시 이렇게 진행을 해도 괜찮을까요!? 다른분들 의견은 어떠신가용 편하실때 남겨주세요!

**Comment by EunjiShin** [comment]
> 현재 Member 부분에는 hard 모드 외 , 따로 on / off 에 대한 stauts 관리가 존재하지 않아서 만약 해당 컬럼을 Member 에 다 추가한다면 많이 뚱뚱해질 것 같단 생각을 했어요!

@JoeCP17 
혹시 Member가 뚱뚱해지면 어떤 점이 문제일까요? 

테이블에 불필요한 컬럼이 많아져 Null값이 많아지거나, 컬럼간 연관이 없어 복잡도가 높아져 인덱스 적용이 어렵다 등의 상황이면 컬럼을 분리하는 것이 좋을 듯 한데, 현재 저희 상황은 그렇지 않은 것 같아서요! 

1. `카테고리 전체에 즐겨찾기 자동 삭제 모드`는 카테고리에 종속된 on/off값이니, `친구 알림 , 모드관리, 읽은 즐겨찾기 자동삭제 설정`이 Member에 추가될 듯 한데, 이 친구들은 Member 테이블 안에서 항상 true or false 값을 갖게 됩니다.

2. boolean 값이라는 것 외에는 공통점도 없는 필드들이라서, 해당 필드들을 하나의 테이블로 분리했을 때 `테이블 성격이 모호`해집니다. 

3. 테이블을 분리할 경우 `조인 연산을 추가로 수행`해야 합니다. 추가적인 연산을 해야 할 정도로 테이블 분리가 필요한 필드들인지 잘 모르겠어요 🤔

의견 편하게 남겨주시면 감사하겠습니다! 🙇‍♀️

**Comment by JoeCP17** [comment]
의견 감사합니당 

제가 생각했던건 은지님이 말씀해주셨던것 처럼 
카테고리 전체에 즐겨찾기 자동 삭제 모드는 카테고리에 종속된 on/off값 , 친구 알림 , 모드관리, 읽은 즐겨찾기 자동삭제 설정 

이렇게 두가지는 성질이 달라 각 Category Table, Member Table 이렇게 두개의 테이블에 넣어주는 것을 처음에 생각을 했었어요!! 

하지만 그렇게되면 on / off 관련해서 Category, Member 두 개의 테이블의 설정정보를 파악해야하니 관리포인트가 늘어날거같아 

하나의 테이블로 묶어 설정관련 on / off 정보를 관리하면 어떨까 생각했었어요! 

제가 알기에는 테이블 설계시 해당관련 정보만 있도록 설계해야하는거로 알고있어서요!! 그래서 status on / off의 정보만 가질 수 있는 테이블을 말씀드렸었습니당

**Comment by EunjiShin** [comment]
@JoeCP17 

RDB 컨셉은 테이블을 나누는게 맞는데, 그렇게 했을 때 얻는 이점보다 공수가 더 큰 것 같아서요! (상세 구현은 깊게 생각안해봤지만요)

Member가 Category별로 알림 설정을 할 수 있는 등 (ex. 백엔드 카테고리에선 알림 받고, 프론트엔드 카테고리에선 알림 안받는다) 알림이 좀 더 세분화된다면 그땐 테이블을 나누는게 좋을 것 같은데, `모드 관리, 읽은 즐겨찾기 자동삭제 설정`처럼 1:1 관계일 땐 테이블 분리로 인해 생기는 관리 포인트와 성능 이슈가 더 생기지 않을까요? 원래는 select 문 한번으로 해결될 것을, 이젠 join을 포함해야 하니까요!

또, 현재 피클리 기획상 Member와 Category는 1:N, Member와 Friend는 N:M, Member와 하드모드 & 즐겨찾기 자동 삭제는 1:1 관계입니다. 이렇게 다른 관계의 데이터들을 하나의 테이블로 합치면 데이터의 중복이 너무 많이 발생해요.

<img width="1268" alt="스크린샷 2023-03-08 오후 12 02 16" src="https://user-images.githubusercontent.com/38103085/223609002-6693319f-495f-4da3-8cb6-fa03d7edc995.png">

이렇게요! (하나의 테이블로 관리한다고 하셔서 이렇게 이해했는데, 혹시 다른 설계 말씀하신거라면 피드백 부탁드려요! 😀)

테이블을 분리하면서 데이터 중복을 해결하려면, 각 관계별로 모드 관리 테이블을 각각 사용해야 합니다.
(ex. Member-Category 삭제 모드 관리 테이블, Member-Friend 알림 관리 테이블 등)
이렇게 되면 현재 방식 (모드 기능 테이블을 분리하지 않고, 있는 테이블에 컬럼을 추가하는 방식)과 다를게 없어지구요 🤔

> 하지만 그렇게되면 on / off 관련해서 Category, Member 두 개의 테이블의 설정정보를 파악해야하니 관리포인트가 늘어날거같아
하나의 테이블로 묶어 설정관련 on / off 정보를 관리하면 어떨까 생각했었어요!

라고 말씀 주셨는데, 모든 on / off 기능에 동시에 접근해야 하는 기능이 없어서, 한번에 두 테이블을 전부 파악해야 하는 유스케이스는 없는 것 같습니다. 현재 UI 상으로는 on/off 관련 기능들이 전부 다른 페이지, 다른 API에 분리되어 있으니까요!
(ex. 카테고리 자동 삭제 모드는 카테고리 관리 페이지에서만, 친구 알림은 친구 목록 페이지에서만.. 등등)

오히려 하나의 테이블로 묶으면 현재로썬 연관 없는 정보라는 느낌이 강한 것 같아요.
자동 삭제 모드와 하드 모드, 친구 알림 수신 여부는 boolean 값이라는 것 외에는 모두 다른 기능이니까요..!

혹시 제가 잘못 이해했거나, 테이블 하나로 모드를 관리하되 구현은 다르게 할 수 있는 방법이 있다면 코멘트 부탁드립니다~! 👽

**Comment by JoeCP17** [comment]
@EunjiShin 

으음 말씀해주시니 뭔가 납득이 되는것 같아요 오우... 상세하게 그림까지 감사합니다 은지님 

유스케이스 방면으로 본다면 확실히 은지님이 말씀하신게 더 어울릴거같긴해요!! 

현재 저희가 나온 정책에 맞게 먼저 설계하고 그 후에 찢어도 추후 마이그레이션하면되니까 무리는 없을거 같긴 해요!! 

저도 딱 두가지로 고민했던거 같아요! 현재 정책별 유스케이스에 따르느냐 vs 추후 진행될 확장까지 고려해서 설계하느냐 

현재까지 저는 항상 후자의 입장에서 생각했어서, 그렇게 더 생각했던 것 같아요!! 

그림까지 보여주시면서 같이 고민해주셔서 감사해용 현재 말씀해주신 방면으로 진행해도 괜찮을거 같아용

**Comment by EunjiShin** [comment]
@JoeCP17 
ㅋㅋ 아닙니다.. 스프레드 시트에 휘갈긴 것 뿐인데용 😀

혹시 의빈님께서 처음 생각하셨던 설계를 공유해주실 수 있으신가요? 
전 위에 예시 첨부드린 것처럼, 하나의 테이블로 합쳤을 때 데이터 정합성이나 중복값, 조작 (CUD)시 발생하는 불편함 등을 고려했을 때 관리하기 어렵다고 생각했거든요 🤔

말씀하신 것처럼 확장성도 설계의 중요한 부분 중 하나이니, 제 방식과 의빈님의 방식을 적당히 섞어서 더 좋은 설계를 만들 수 있을 것 같아요!
또 생각하신 추후 발생할 수 있는 확장 요소도 어떤 기능이 있을지 궁금합니다! 👀 

^.ㅠ 얼른 개발 시작하셔야하는데 논의가 너무 길어지네용.. 시간내서 같이 고민해주시고 답변해주셔서 감사해요 👍👍👍
