### ISSUE TITLE
[hotfix] 버전 어노테이션 문제를 수정합니다.

### ISSUE THREAD

**Issue by JoeCP17** [pickly-team/pickly-backend#59]
@EunjiShin  @litsynp  @JerryK026  @SoobinJung1013 

버전 어노테이션을 이용해 테스트 하기 위해 구현한 API 외, 현재 저희 서비스 API 접목했을때 아래와 같은 이슈가 발생합니다. 

급하게 해당 부분 수정을 진행할동안 혹시나 구현하거나 사용하실때 아직은!!! 사용 자제해주시면 될것 같아요 ㅠ 

빠르게 문제파악 진행해보겠습니당 

![image](https://user-images.githubusercontent.com/76832303/224356680-7fe12483-b7af-4518-9239-788203b16d4a.png)

**Comment by JerryK026** [comment]
확인했습니다~

**Comment by EunjiShin** [comment]
++ Swagger와의 충돌 이슈 확인 필요

<img width="603" alt="스크린샷 2023-03-15 오후 9 26 35" src="https://user-images.githubusercontent.com/38103085/225308529-9cd48324-165a-446a-b1d5-b57bb2ee9de5.png">

**Comment by EunjiShin** [comment]
++ 쿼리 콘솔 로그 설정과의 충돌 이슈 확인 필요

(버전 작업 이전엔 show_sql 설정이 동작함 / 이후엔 로그 안찍힘)

**Comment by JoeCP17** [comment]
진행상황 공유 

1. 버전 어노테이션 문제 해결 
- 원인 
  - 기존 설정된 AccessAutoConfig 로 설정된 항목중 WebMvcConfigurationSupport를 상속받아 Intercept설정을 하는데, 이부분이 
      Security 설정과 충돌이 발생해 Race condition이 발생되는 이슈 

- 해결 
   - Accept가 아닌 header부분에 version으로 선언하여 Accept권한은 security에게 위임하여 충돌 방지 

**2. Swagger 이슈 ( 해결중 )** 
- 원인 
    - 1번의 문제와 같은 문제 
    - Swagger Open API의 경우도 WebConfiguration 상속을 받는데, 이 부분을 기존에 먼저 상속받아 사용하고 있기에 발생되는 이슈
