### ISSUE TITLE
[고민] 노말 하드 모드 진행에 대한 정책

### ISSUE THREAD

**Issue by ww8007** [pickly-team/pickly-backend#64]
## 고민

현재 노말 모드와 하드 모드에 대해서 정책이 좀 비어 있는거 같아요
1. 하드 모드 진행에 있어서 삭제되는 북마크들이 매일 기준으로 달라질 것 같은데
이에 대해서 처리를 어떻게 할건지? -> 동일하게 노말 모드에서도
(매일 12시를 기준으로 3일 이내 삭제되는 북마크 개수?)

2. 노말 모드에서 첫번째 아이콘에 대한 몇일째 진행중인지가 과연 의미가 있는 데이터일지?

3. 모드 변경을 누를 때 마다 진행중인 일자가 초기화가 되는 것인지? 

@litsynp 님이 페이지 작업을 해주시다가 말씀을 해주셔서 정해보는게 좋을 것 같아서
의견 주시면 감사하겠습니다! 🙇‍♂️

<div style={{display: flex, width="100%"; justify-content: space-between;}}>
 <img width=300 src="https://user-images.githubusercontent.com/54137044/224505290-fce6ea18-9236-4413-b36a-1d95c29a78a7.png"/>
<img width=300 src="https://user-images.githubusercontent.com/54137044/224506269-cebd0228-99b5-4966-a1cb-465939fa65eb.png"/>
<div>

**Comment by EunjiShin** [comment]
> 1. 하드 모드 진행에 있어서 삭제되는 북마크들이 매일 기준으로 달라질 것 같은데
이에 대해서 처리를 어떻게 할건지? -> 동일하게 노말 모드에서도
(매일 12시를 기준으로 3일 이내 삭제되는 북마크 개수?)

저는 특정 모드로 전환 후 지금까지의 누적 삭제 개수라고 생각했어요!
ex. 2023년 3월 1일에 하드모드로 전환한 경우, 3월 1일부터 오늘까지 하드모드에 의해 자동으로 삭제된 북마크 개수 출력

해당 값은 실시간 업데이트되는게 아니라, API 호출할 때 카운트하구요.
ex. 유저가 마이 페이지를 보고 있을 때 하드모드에 의해 북마크가 삭제된 경우, 마이페이지를 새로고침 하면 삭제된 북마크 개수가 업데이트된다.

하드모드의 취지가 "아카이빙한 북마크를 놓치지않고 팔로업하기 위함" 인 만큼, 유저의 동기 부여를 위해 현재까지 삭제된 개수를 전부 보여주는게 좋을 것 같다고 생각했어요

> 2. 노말 모드에서 첫번째 아이콘에 대한 몇일째 진행중인지가 과연 의미가 있는 데이터일지?

해당 값은 하드 모드 UI와 통일하기 위해 넣었습니다! (초기 화면 짤 때)

말씀하신 것처럼 크게 유의미한 데이터는 아니나, 피클리의 기획 의도를 고려하면 또 불필요한 데이터는 아닌 것 같습니다.
00일 동안 내가 북마크를 잘 읽지 않아서 00개의 알림이 울렸다~ 로 알림 개수와 연관지으면 동기 부여가 적당히 될 것 같아요.

다만 피클리 전체 기능에서 중요도를 따졌을 때, 우선순위가 낮은 기능이므로 해당 기능을 구현하기 위해 DB 설계가 복잡해지거나 개발 공수가 크다면 생략해도 좋다고 생각합니다~

> 3. 모드 변경을 누를 때 마다 진행중인 일자가 초기화가 되는 것인지?

넵 처음 UI 짤 때는 그렇게 의도했습니다!

**Comment by ww8007** [comment]
> > 1. 하드 모드 진행에 있어서 삭제되는 북마크들이 매일 기준으로 달라질 것 같은데
> >    이에 대해서 처리를 어떻게 할건지? -> 동일하게 노말 모드에서도
> >    (매일 12시를 기준으로 3일 이내 삭제되는 북마크 개수?)
> 
> 저는 특정 모드로 전환 후 지금까지의 누적 삭제 개수라고 생각했어요! ex. 2023년 3월 1일에 하드모드로 전환한 경우, 3월 1일부터 오늘까지 하드모드에 의해 자동으로 삭제된 북마크 개수 출력
> 
> 해당 값은 실시간 업데이트되는게 아니라, API 호출할 때 카운트하구요. ex. 유저가 마이 페이지를 보고 있을 때 하드모드에 의해 북마크가 삭제된 경우, 마이페이지를 새로고침 하면 삭제된 북마크 개수가 업데이트된다.
> 
> 하드모드의 취지가 "아카이빙한 북마크를 놓치지않고 팔로업하기 위함" 인 만큼, 유저의 동기 부여를 위해 현재까지 삭제된 개수를 전부 보여주는게 좋을 것 같다고 생각했어요
> 
> > 2. 노말 모드에서 첫번째 아이콘에 대한 몇일째 진행중인지가 과연 의미가 있는 데이터일지?
> 
> 해당 값은 하드 모드 UI와 통일하기 위해 넣었습니다! (초기 화면 짤 때)
> 
> 말씀하신 것처럼 크게 유의미한 데이터는 아니나, 피클리의 기획 의도를 고려하면 또 불필요한 데이터는 아닌 것 같습니다. 00일 동안 내가 북마크를 잘 읽지 않아서 00개의 알림이 울렸다~ 로 알림 개수와 연관지으면 동기 부여가 적당히 될 것 같아요.
> 
> 다만 피클리 전체 기능에서 중요도를 따졌을 때, 우선순위가 낮은 기능이므로 해당 기능을 구현하기 위해 DB 설계가 복잡해지거나 개발 공수가 크다면 생략해도 좋다고 생각합니다~
> 
> > 3. 모드 변경을 누를 때 마다 진행중인 일자가 초기화가 되는 것인지?
> 
> 넵 처음 UI 짤 때는 그렇게 의도했습니다!

---
@EunjiShin
 
---

1.흠 그렇다면 삭제된 리스트에 대해서도 보여주는 것도 좋을 것 같은데 
(단순히 삭제 된 개수들 보다 내가 어떤 것들을 놓쳤는지?) 이 부분은 고민을 좀 더 해봐야겠네요
---
2. 저도 UI 통일성 관점에서는 환영 입니다 (피그마 안고쳐서 행복 🥳)
구현 여부에 대해서는 이쪽 API 담당하시는 분이 검토해주시면 좋겠네요!
---
3. 그럼 정말로 변경을 원하는 것이 맞는지에 대한 확인 여부 modal, bs가 있으면 좋겠네요
뭔가 기껏 지속해왔던 일수가 사라지면 마음이 아플 수도 있으니...? 
한 번 피그마에 추가해보도록 하겠습니다!

근데 markdown이 의도한 대로 달리지 않네요 🫠

**Comment by JoeCP17** [comment]
1. 하드모드 북마크의 경우 지속적으로 계속 업데이트 해주는 것도 나쁘지 않을거 같아요!! 추후 이부분은 검토해보고 괜찮다면 레디스 써보는 것도!? 

2. 음... 저는 없어도 상관은 없지만 그래도 있으면 좋을것 같단 생각이 들었어요!! 노말모드라도 내가 얼마만큼 진행하고 있는지, 경과된 시간을 보면 노말이라도 얼른 해야겠네? 라는 생각이 들거 같거든요!! 

3. 각 모드별 경과 일자를 따로 관리해서 노말모드에서는 내가 이정도 시간이 경과했고 주요 북마크를 기록해둔 하드모드에서는 얼마만큼 남았는지 따로 관리한다면 유저분들이 이 서비스를 이용하실때 나름대로 자유도 높게 계획하실 수 있도록 제공해드릴 수 있을 것 같아 따로둬도 괜찮을 것 같아요!

**Comment by EunjiShin** [comment]
@litsynp 정기미팅 의견

- 매번 count 쿼리 날리는 것은 부담스럽다! bookmark 카운트를 위한 테이블을 별도로 만들어서 카운트 수 관리 컬럼을 따로 만드는건 어떨까?

**Comment by SoobinJung1013** [comment]
제 생각에는
- 저는 1번은 중요도가 높지 않은 것 같아서 생략해도 될 것 같습니다. 
- 2번도 마찬가지로 중요도가 높지 않지만, 있으면 좋을 것 같습니다. (1번보다는 2번이 우선순위가 높아 보입니다!)

**Comment by EunjiShin** [comment]
**[ 정기 회의 논의 내용 ]**

1. 하드모드에 의해 자동 삭제된 북마크 수를 보여주는 기능 구현 하는 것으로 결정
:: count 수 관리하는 컬럼을 이용한다! 
:: 추후 기능 확장 시, count 관련 필드를 관리하는 테이블로 migration하는 것도 결정한다

2. 노말 모드에서 몇일째 진행중 기능 구현 하는 것으로 결정
:: 출석표 기능은 킵 -> develop 할 때 고민하자

3. 모드 변경을 누를 때 마다 진행중인 일자가 초기화가 되는 것인지?
:: 초기화 한다면 -> FE는 bs 또는 alert 등 경고문구 추가 필요

**Comment by EunjiShin** [comment]
@litsynp 의견 (1번 기능 관련 => 확장성을 고려, 컬럼 말고 테이블로 관리하자!)

API 개수의 차이라기보단 사용자 테이블은 최대한 북마크 관련 기능은 배제하고
북마크쪽 도메인에 붙이고 싶어서요
나중에 분리하기도 더 쉬울 것 같아서?
예를 들어 지금은
모노리식이지만
pickly-bookmark-api
이런식의 마이크로서비스가 생긴다면
분리되어있을 때 마이그레이션 작업이 더 편리하니
그래도 뭐 분리할 가능성이 없다고 가정하고 사용자 테이블에 컬럼이 추가가 많이 되어도 상관이 없다면
컬럼에 추가해도 좋을듯합니당

**Comment by EunjiShin** [comment]
**[ 2023 / 3 / 18 ]**

<img width="324" alt="스크린샷 2023-03-20 오전 11 16 54" src="https://user-images.githubusercontent.com/38103085/226231407-fa199523-a821-4925-9b17-d6a1cb019cf9.png">

기획 및 UI 변동으로 위 기능 삭제되었습니다.
