### ISSUE TITLE
[제안] PR 코드리뷰 관련 룰

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#66]
## 개요

스프린트가 진행되면서 PR이 많이 올라오고 있는데, 피드백을 주고 받는 과정에서 진행이 조금 더뎌지는 감이 있는 것 같습니다.
적극적인 피드백은 팀원 모두가 지향해야 하는 좋은 개발 문화지만, 일정 관리를 위해 어느 정도의 우선순위는 세워두는게 좋을 것 같습니다.

## 제안 

`Pn 룰`을 도입해 피드백의 우선 순위를 매기면 좋을 것 같습니다.

`P1` : 중요. 꼭 반영해주세요 / 해당 코멘트를 적극적으로 확인해주세요
`P2` : 보통. 웬만하면 반영해주세요 / 그럴 수 없다면 이유를 설명하거나, 후속 이슈를 파서 반영해주세요.
`P3` :  사소. 정말 사소한 의견입니다. 아무런 의견을 달지 않아도 상관 없습니다.

덧붙여 코멘트를 추가할 때, 왜 이런 코멘트를 드렸는지에 대한 배경 설명 / 의도를 추가해주시면 팔로업이 더 빨라질 것 같아요~

## 레퍼런스
https://blog.banksalad.com/tech/banksalad-code-review-culture/

**Comment by ww8007** [comment]
좋은 것 같습니다!
리뷰를 받은 내용에 대해서 중요도를 판별하면 목적성이 확실하게 구분될 것 같습니다 😃

**Comment by JoeCP17** [comment]
동의합니당 .... 중요도 판별!

**Comment by SoobinJung1013** [comment]
저도 너무 좋은 것 같습니다 !
