### ISSUE TITLE
[bug] VersionController용 RequestHandlerMapping이 @VersionResource 말고 다른 것도 잡고 있는 것 같아요

### ISSUE THREAD

**Issue by JerryK026** [pickly-team/pickly-backend#72]
<img width="1068" alt="image" src="https://user-images.githubusercontent.com/55067949/225245505-516f9295-8d95-4066-beb2-fdfdfdd9dafe.png">
현재 큰 영향을 주는 건 아니지만 서비스 배포시 에러 로그를 저장하기 시작하면 서버 단에서 무의미한 에러를 쌓으면서 추후에 혼동을 줄 수도 있다고 판단되어 보고합니다.

**Comment by JoeCP17** [comment]
저 부분의 경우 플로우는 다음과 같습니다. 

1. API 모듈 내 WebConfig로 extend받은 항목에 의해, Version 부분에서 이전에 접근 가능하도록 할당된 {Version_Access_Key} 부분으로 Version 어노테이션이 붙은 API 를 관리합니다. 

2. 관리되는 동안 Controller 내, API들을 스캔하며 붙은항목은 할당 , 없는 항목은 Null로 할당되어 구분지어집니다. 

3. 추후, 각 API별 버전 리소스를 잡고있는 부분과 아닌 부분을 구별할 수 있을 것 같아 추가 했었는데 불필요하다면 제거해도 무방합니다.
