### ISSUE TITLE
[bug] 프로필이 올바르게 적용되지 않는 이슈

### ISSUE THREAD

**Issue by litsynp** [pickly-team/pickly-backend#81]
프로필이 올바르게 적용이 되지 않는 이슈가 있습니다.

무조건 test 프로필이 적용되어 DB 설정을 아무리 고쳐도 실행이 안됩니다.

on-profile을 명시해줘야 프로필이 작동되는 듯 해서 추가가 필요.

**Comment by EunjiShin** [comment]
<img width="920" alt="스크린샷 2023-03-20 오후 10 11 47" src="https://user-images.githubusercontent.com/38103085/226348804-2c576959-55a3-49f7-8516-5c8eda1e8825.png">

이쪽 설정 때문인 것 같습니다! 

하드코딩된 부분을 자동으로 프로필 로드하도록 수정하면 될 것 같아요.
@JoeCP17 님 혹시 저부분 하드코딩으로 박힌게 멀티 모듈 관련 설정 때문일까요?

**Comment by litsynp** [comment]
더 이상 유효하지 않아 issue close합니다.
