### ISSUE TITLE
[고민/DB] 알림 내역 테이블 설계

### ISSUE THREAD

**Issue by EunjiShin** [pickly-team/pickly-backend#91]
## 개요
북마크 알림 내역을 저장하는 테이블 설계 필요

## 관련 작업
#74 

## UI
<img width="571" alt="스크린샷 2023-03-22 오전 12 58 16" src="https://user-images.githubusercontent.com/38103085/226666900-28659414-d252-4516-89a3-70e2e32cbf25.png">

## 고려사항
1. 해당 알림의 읽기 / 삭제 처리가 필요함 -> PK 또는 UK 로 레코드를 특정할 수 있는 값이 필요
2. 유저별 알림 내역 관리 필요 -> Member FK 필요 -> 근데 알림은 개수가 많을거고, Join이 필요하진 않으므로 논리 FK로 가져가도 될듯
3. 특정 알림 내역을 눌렀을 때, 해당 알림이 나타내는 북마크 페이지로 redirect 되어야 한다 ->  Bookmark 논리 FK도 필요할 듯

## 고민 사항
- Member, Bookmark 정보가 필요한데, 물리 FK를 둘 것인지 vs 논리 FK를 둘 것인지?
- (지금은 MVP에서 제외되었지만) 하드 모드 알림 내역, 노말 모드 알림 내역, 친구 알림 내역을 같은 테이블에서 관리할 것인지?

**Comment by EunjiShin** [comment]
(부가설명)
알림 내역을 눌렀을 때, 해당 알림이 가리키는 북마크 상세 페이지로 이동하는 기능 관련

- Bookmark 상세 조회 API call을 위해 Bookmark 식별자가 필요
- 유저가 다르면 같은 url이라도 PK가 다름 (ex. A유저의 a url 북마크와 B유저의 a url 북마크는 다른 레코드)
- 따라서 PK로만 접근 가능한 상황

**Comment by EunjiShin** [comment]
저는

**1. Member, Bookmark 정보는 논리 FK로 관리한다**
- 조인 테이블의 다른 컬럼값 필요 없고, ID 값만 필요하기 때문 (특정 유저의 알림 내역 조회 / 북마크 상세 페이지 조회 request에 쓰일 ID)

**2. 하드 모드 알림 내역, 노말 모드 알림 내역, 친구 알림 내역은 같은 테이블에서 관리하고, 필요하다면 컬럼으로 알림 타입을 구분한다**
- FCM 구조상 title / body 로 알림이 구성될 거라 그대로 컬럼으로 가져가도 되지 않을까..!
- 알림 타입이 나뉘긴 하지만, 알림 내역 조회 / 삭제는 알림 타입에 관계가 없음. 기껏해야 타입별 알림 내역 조회처럼 필터링하는 기능..? 

이렇게 생각하고 있습니다!

**Comment by JoeCP17** [comment]
[ P1 ] 
추가적으로 몇개 사항을 더 생각해봐야해요! 

FCM 사용시 JWT 처럼 각 유저별 디바이스에 대한 접근 token값을 제공하는데 이 토큰 값을 서버내 데이터베이스에서 관리해줘야 해요! 

1. 각 유저별 디바이스 Token 값을 저장할 수 있어야한다. 
2. Topic 을 활용한 메시지 전송 시에도 해당 토픽 값 또한 서버에서 관리해야 하기에 이를 고려한 토픽 테이블도 필요해요!! 
3. 가상면접 책에서도 나오는데 알림을 고려했을때 고정적으로 작성되는 메시지에 대한 Template 테이블도 있으면 좋을 것 같아요! ( 이는 참고 사항 )

**Comment by JoeCP17** [comment]
< 수정 > 

로그 관리만 주로 놓고 판단했었을때 은지님 의견에 동의합니다 

어차피 로그내역에서는 성공 유무와 발송 정보만 파악하면 되기 때문에 그렇게 가져가도 괜찮다고 생각이 들었어요! 

만약? 구성을한다고 한다면 은지님 의견에 붙여 이렇게 해볼 수 있을 것 같다고 생각이 들어요!  아래는 대략입니다! ( 논의는 해봐야 한다. ) 

< 생각했을때 필요할 것 같다는 요소 > 
table 명 : notification < 가제 > 
=> Id 
=> member_id 
=> bookmark_id 
=> notification_category : varchar <--- 하드 , 노말 , 알림 구분을 위한 카테고리 
=> title 
=> body 
=> img_url <-- 현재는 이모지로 알고있는데 이모지 or 이미지를 사용한다면 img_url 항목 
=> is_success 
=> is_deleted : bit(1) 


< 의문이 들수도 있을 것 같은 포인트 의견 > 
1. is_deleted
해당 부분은 논리적 삭제 부분때문에 추가를 해봤어요!! 
로그의 경우 이 로그를 통해 유저들이 어떤 북마크에 관심있는지 추후 카테고리별로 추출하여 추후 추천 항목을 만든다고 했었을 때 유용하게 사용할 수도있기에, 메시지를 물리적 삭제로 하는것보단 flag 값을 기반으로 남겨두면 어떨까? 라는 생각을 했었어요 


< 이 부분은 어떤가요? - 의견제시 > 
FCM 발송 이후 Response로 서버에 몇개가 성공했는지와 실패했는지, 실패했다면 어떠한 에러인지를 BatchResponse라는 바디에 담아 내려주고 있어요! 추후 실패케이스 재 전송을 하거나 했을때 이부분을 사용해야 하기에, 이 부분을 어떻게 하면 좋을 지 생각해봤어요! 

테이블 분리 
예를 들어 notification_log < 가제 > 테이블을 두고 

=> notification_id 
=> message_id <--- FCM 에서 발송 요청시 각 메시지별로 id값을 내려주고 있어요! type: String  이부분 구별을 위해 한번 추가해봤어요! 
=> error_message 
=> success_count 
=> failed_count

**Comment by EunjiShin** [comment]
소중한 의견 감사합니다 조! 🥳 아주 꼼꼼하십니다 굿굿
의견 남겨주신 것 관련해서 몇 가지만 같이 체크해보면 좋을 것 같아요~~ ❗️ 조 말고 다른 팀원 분들도 체크 부탁드립니다❗️ 

[ 📌 시작 전 체크 ]

알림 내역 테이블은 **로그 목적이 아니라, 기능에 실제 사용되는 테이블**입니다!
푸시 알림은 일회성이라서, 테이블에 따로 저장하지 않으면 알림 기록들이 전부 사라질거에요.
저희는 유저가 삭제한 알림만 삭제되도록 하고, 나머지는 알림 관리 페이지에서 보여줘야 하기 때문에 테이블에서 관리해야 합니다.
로그와는 별도로 생각해주세요~


[ 📌 남겨주신 의견 관련 질문 ]

**1. < 생각했을때 필요할 것 같다는 요소 > 관련**
> => notification_category : varchar <--- 하드 , 노말 , 알림 구분을 위한 카테고리

여기는 int으로 관리하면 어떨까요? 
enum으로 관리하는 것도 방법일 것 같은데, 알림 종류가 수정/추가될 때마다 ddl을 날려야 한다는 점이 조금 부담스러워서요!
**@Converter를 이용해, Java에서 Enum으로 관리하고 DB에는 int로 저장**하면 어떨까 싶어요. 

사실 알림 종류가 변경되는 일이 많지 않을 것 같아서ㅎㅎ DB단위에서 enum으로 해도 괜찮을 것 같지만, String보다는 int를 사용하는 것이 데이터 저장 공간도 적고 성능 상 더 유리하니 int로 저장해보는 것도 좋은 시도일 것 같은데 어떻게 생각하시나요? 

> => is_success

푸시 알림 성공 여부를 따로 저장하려면 비동기처리가 힘들지 않을까요?
푸시 알림이 종료되어야만 성공 여부를 판단할 수 있으니까요. 
또 해당 테이블이 단순 알림 로그 용도가 아닌, 유저의 알림 내역 정보를 기록하고 화면에 보여주는 용도이기 때문에 실패한 알림을 저장할 필요는 없을 것 같습니다. 

알림 발송 중 실패한 경우는 어플리케이션단에서 재발송 시도를 하거나, 또는 실패 로그를 따로 남기는 정도로 충분하지 않을까요?
확인 부탁드려요! 🙇‍♀️

---

**2. < 의문이 들수도 있을 것 같은 포인트 의견 > 관련**

> => is_deleted : bit(1)

원래 쓰던 deleted_at을 bit(1)로 변경하신 이유가 있을까요? 
(현재 피클리의 모든 테이블은 created_at, updated_at, deleted_at 컬럼을 기본 컨벤션으로 들고있습니다)

---

**3. < 이 부분은 어떤가요? - 의견제시 > 관련**

네 실패 케이스 관리 프로세스가 필요할 것 같습니다~
그런데 제가 알기로 message id는 푸시 알림별로 매겨지는 값인데, 혹시 아닌가요?
message id별로 success_count와 fail_count를 관리할 필요가 없을 것 같아서요~ (무조건 1 아니면 0이니까요)

**Comment by JoeCP17** [comment]
호우... 은지님 체크 감사합니다 :) 
정신이 없어서 누락하거나 잘못 체크하고 있었던 항목들도 제가 있어서 먼저 죄송하다는 말씀 올립니다 ㅠ_ㅠ 

댓글 달아주신 사항에 답글 남기면 다음과 같습니다. 

1. notification_category 
- 맞아요! 은지님 말씀처럼 int로 관리해도 무방할 것 같습니다 ! 이 부분은 조금 더 명시적으로 각 칼럼마다 표기되면 어떨까 해서 생각했던건데 id값으로 해서 구분지어도 괜찮을 것 같아요! 

2. is_success 
해당 부분은 FCM -> Client까지가 아닌, 요청 전송시 ( Server -> FCM )까지의 성공유무를 담아보고자 넣었던 항목이었어요!! 
말씀 해주신것 처럼 알림 내역/ 로그를 별도로 관리한다고 가정한다면 뺴고 심플하게 푸시에 대한 내용만 들어가도 괜찮습니다!! 

3. is_deleted 
- deleted_at을 체크못한 실수로 발생한 것 같습니다 ㅠㅠ deleted_at으로 가져가도 무방합니다! 

4. 실패케이스 
저 부분은 고민을 많이했었어요!! 
개인별로 보낼때는 말씀하신것처럼 1 , 0 두가지 케이스겠지만 만약 마케팅이나 전체적으로 보내는 푸시가 나중에 추가되거나 할 경우 발송 시 각 유저들마다 성공 실패 유무 횟수를 파악해야 하는데 그럴때 어떻게 하면 좋을까? 생각을 하다 넣게 되었던 항목이었습니다 

전체 일괄 푸시 전송 계획이 없다면 추가하지 않아도 무방합니다!!! ( 현재 정책에 존재하지 않는다면 )
