### ISSUE TITLE
[고민 / DB ] 앞으로 진행될 푸시에 관련된 테이블에 대해 고민해야 할것이 있습니다. 

### ISSUE THREAD

**Issue by JoeCP17** [pickly-team/pickly-backend#95]
< 메시지 발송을 위한 타겟팅 멤버 고민 > 
FCM 푸시에는 다음과 같은 메시지 발송 정책이 있습니다. 

1. TOKEN 을 활용한 푸시 메시지 발송 
2. TOPIC을 활용한 푸시 메시지 발송 

TOKEN , TOPIC 두개를 Firebase에서 알아서 관리해주면 참 좋겠지만! FCM에서 따로 해당 항목에 대해 관리를 해주지 않기에 이를 서버에서 관리해야해요! ( 공식문서 참고 ) 

푸시 메시지를 발송하기 위해 TOKEN 과 TOPIC을 어떻게 관리할 것인지에 대한 테이블 정책이 필요할 것 같습니다! 

< 푸시 템플릿에 대한 고민 > 
가상면접사례 책  챕터 10에서도 푸시 관련 아키텍쳐 내용이 나오는데요 
푸시를 보내는 시점에 현재는 관련 정책이 제공되어 있진 않지만 다음과 같은 부분 때문에 따로 푸시Template 테이블도 있으면 좋겠다고 생각을 했어요! 

ex ) %s 님 환영합니다!  / %s 님 하드모드 종료까지 3일 남았어요 / %s 님 노말모드 종료까지 3일 남았어요! 

그렇기에 이 부분에 대해서도 한번 고민을 나눠보고 테이블을 따로 두는게 맞을지 한번 고민 같이 해보면 좋을 것 같아요!! 

템플릿의 경우 정책이 적용되고 선정이 되면 사실 정책이 변경 될때까지 데이터의 변동은 없기에 Redis를 활용해 캐싱데이터로 넣어놔도 좋을 것 같아요!! 

<결론> 

1. TOPIC / TOKEN 에 대한 관리 테이블 구성 
2. FCM Notification Template 에 대한 관리 테이블 구성 or 레디스 접목

**Comment by EunjiShin** [comment]
**1. TOPIC / TOKEN 에 대한 관리 테이블 구성**

TOPIC 방식의 푸시 알림은 피클리의 알림 기능과 맥락이 다르다고 생각합니다. 
언젠가는 TOPIC 방식이 필요한 알림 기능이 추가될 지도 모르지만, 지금은...굳이? 
기획이나 기능 요구사항 자체가 아예 없는 상황이라, 확장성을 고려해서 미리 짜두기에도 애매한 것 같아요. (지금 짜봤자 나중에 실제 기능이 추가되면 높은 확률로 수정될테니까)

현 MVP 상황에선 TOKEN 관리 테이블 정도만 구성해도 충분할 것 같습니다. 다른 분들 의견도 궁금하네요
(TOPIC 관리 테이블은 user_id, topic_id 정도만 있을 것 같아서.. 나중에 추가하기 어려울 것 같지도 않구요)

**2. FCM Notification Template 에 대한 관리 테이블 구성 or 레디스 접목**

RDB에 저장하고, Redis 캐시를 이용해 푸시 알림 기능에 활용하자는 의미신거죠? 
RDB에 저장된 템플릿이 변경될 때 캐시 업데이트를 쳐주는 거구요. 
저는 좋습니다! 👍 겸사겸사 FCM token의 관리에도 Redis를 활용하면 되겠네요ㅎㅎ 굿굿

**Comment by JoeCP17** [comment]
은지님 답변 감사합니다!! 

1. TOPIC / TOKEN 에 대한 구성 
- 앗 맞아요!! 토픽은 당장 사용될 일이 없다고 하면 따로 구상하지 않아도 되지만 추후를 고려해 한번 의견을 내봤었어요! 
  아직까지 모호한 상황이라고하면 TOKEN 의 값만 관리되도록 테이블 구상해도 좋을 것 같습니당 


2. FCM Notification Template 에 대한 관리 테이블 구성 or 레디스 접목
- 맞아요 ㅎㅎ 저도 처음 레퍼런스 찾아보며 구현했을떄 그렇게 많이 사용을 하더라구요!! 그부분에서 영감을 받아서 사용하고 있었어요!!
